model = "gpt-5.5"
model_reasoning_effort = "medium"
service_tier = "priority"

[features]
memories = true

[projects."/Users/eason_tseng/playground"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/asurada"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/game-management-platform"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/platform-backoffice-frontend"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/n8n"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/go-ddd-core"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/mcp-server"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/go-ddd-adapters"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/telegram"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/arkham-docs-server"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/ai-platform"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/game-management-platform"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/bbgp/cloud-service"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/字典檔/dict-midori"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/mcp-server/stellaris-mcp-server"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/字典檔/dict"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/midori/cloud-service"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/reports"]
trust_level = "trusted"

[projects."/Users/eason_tseng/playground/project/dict"]
trust_level = "trusted"

[plugins."github@openai-curated"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 4
